[package]
name = "tiny-business-simulator"
version = "0.3.1"
edition = "2021"

authors = ["David Valin <hola@davidvalin.com>"]
homepage = "https://crates.io/crates/tiny-business-simulator"
repository = "https://github.com/DavidValin/tiny-business-simulator"
description = "A simple .txt file business simulator that allows you to setup financial goals and see the targets you will need to meet to achieve your business goals"
keywords = ["business", "simulation", "entrepreneur", "terminal", "simple"]
license-file = "LICENSE"
readme = "README.md"

[[bin]]
name = "tiny-business-simulator"
path = "src/cli.rs"

[dependencies]
ratatui = "0.30"
crossterm = "0.29"
unicode-width = "0.2"
